version: '2'
services:
    laika:
        image: medigo/laika
        build: .
        command: go run main.go run
        links:
            - mysql
        environment:
            LAIKA_MYSQL_HOST: mysql
            LAIKA_MYSQL_PORT: 3306
            LAIKA_MYSQL_USERNAME: root
            LAIKA_MYSQL_PASSWORD: root
            LAIKA_MYSQL_DBNAME: laika
            LAIKA_TEST_MYSQL_HOST: mysql
            LAIKA_TEST_MYSQL_PORT: 3306
            LAIKA_TEST_MYSQL_USERNAME: root
            LAIKA_TEST_MYSQL_PASSWORD: root
            LAIKA_TEST_MYSQL_DBNAME: laika
            LAIKA_STATSD_HOST: localhost
            LAIKA_STATSD_PORT: 812
            COVERALLS_TOKEN:
    mysql:
        image: mysql:5
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laika
