laika:
    build: .
    command: go run main.go --migrate
    links:
        - mysql
    environment:
        LAIKA_MYSQL_HOST: mysql
        LAIKA_MYSQL_PORT: 3306
        LAIKA_MYSQL_USERNAME: root
        LAIKA_MYSQL_PASSWORD: root
        LAIKA_MYSQL_DBNAME: laika
        LAIKA_STATSD_HOST: localhost
        LAIKA_STATSD_PORT: 812

mysql:
    image: mysql:5
    ports:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laika
